### ISSUE TITLE
Get current user from os/user

### ISSUE THREAD

**Issue by anh** [go-bootstrap/go-bootstrap#1]
this's proabably better alternative http://godoc.org/os/user#Current

**Comment by didip** [comment]
Ah, great question! The reason I did this was because on previous project, I learned that `user.Current()` does not play well with cross-compiler.

But for this project that matter very little, I can change that.

**Comment by cryptix** [comment]
You might want to take a look at [go-homedir](github.com/mitchellh/go-homedir) which doesn't use cgo. It needs a populated environment though.

**Comment by didip** [comment]
For now, I'll leave the current solution. Will reopen when there's a windows user needing this.
