### ISSUE TITLE
Project is generated inside a folder named blank

### ISSUE THREAD

**Issue by brenoc** [go-bootstrap/go-bootstrap#10]
On Ubuntu, when I type:

```
go run main.go -dir github.com/test/test
```

The project is generated at: `$GOPATH/src/github.com/test/test/blank/`, not at `$GOPATH/src/github.com/test/test/` as expected.

**Comment by didip** [comment]
Is commit #11 fixed it for you?

**Comment by brenoc** [comment]
@didip Yes, thanks, @gmas!
