### ISSUE TITLE
Separate app bootstrap from database bootstrap

### ISSUE THREAD

**Issue by rnubel** [go-bootstrap/go-bootstrap#13]
Currently, running `main.go` will both generate the app codebase and bootstrap the database. This works fine for a one-developer workflow, but should a new developer join your project, they'll have to figure out how to manually create and migrate their database. And, after doing some work on #6, I realized my change was a bit pointless -- after all, `main.go` is only run once. The bulk of the database connections are done from the app, [here](https://github.com/go-bootstrap/go-bootstrap/blob/ced05fc3d19ed6f601dc9314f799d5aacd6eccc6/blank/main.go#L33). I could make the same set of changes to the app itself, but that seems unnecessarily redundant. Plus, there's no reason generating an app from a template, like this project does, needs to hit the database.

So, my proposal is to remove the database bootstrap steps from `main.go` (steps 4 and 5b), and move them into the generated app codebase instead. I'm not sure where, exactly -- I come from a Ruby/Rails background and thus immediately think of Rake -- but perhaps a `bin/db` utility that can both `bootstrap` and `migrate`. Plus, the `main.go` script could still go into the app folder and run said utility.

**Comment by didip** [comment]
It's not directly related to your need, but I've added more documentation on the `migrate` command here: https://github.com/go-bootstrap/go-bootstrap/tree/master/blank#running-migrations

**Comment by didip** [comment]
If we go with this proposal, and assuming you are starting a new project,
are you planning on creating the database and test database yourself?

**Comment by rnubel** [comment]
My line of thought is, it's the bootstrap script's responsibility to create the app, and the app's responsibility to manage its own database. Having the bootstrap script do the database creation and initial migration is handy, but requires any database configuration changes (like in #6) to be done in two places, and doesn't provide any tooling for future developers. So, per my proposal, moving the database creation/initial migration into the app would create a single point of database configuration, and unify the db tooling for both the initial bootstrapper and future developers starting the project.

Note that I'm not suggesting the bootstrap process *shouldn't* create the database; just that the code for doing so should live in the app be re-usable.

**Comment by didip** [comment]
I see, seems reasonable... I'll play with this over the weekend.
