### ISSUE TITLE
Setup instructions could be simpler

### ISSUE THREAD

**Issue by nf** [go-bootstrap/go-bootstrap#17]
Since the `go get` step builds `main.go` and puts the binary in `$GOPATH/bin/go-bootstrap`, the instructions could be simpler still:

    # Step 1
    go get github.com/go-bootstrap/go-bootstrap

    # Step 2
    $GOPATH/bin/go-bootstrap -dir github.com/$GIT_USER/$PROJECT_NAME

    # Step 3
    cd $GOPATH/src/github.com/$GIT_USER/$PROJECT_NAME && go run main.go

**Comment by relistan** [comment]
:+1:  This is how I used it, also.

**Comment by didip** [comment]
Done!
