### ISSUE TITLE
Fatal error when trying to run main.go 

### ISSUE THREAD

**Issue by Qfulsher** [go-bootstrap/go-bootstrap#22]
I am following the tutorial on the readme and everything works until the last command, if I try to run main.go in the new project I get the following error message: 

FATA[0000] pq: password authentication failed for user "{user-name}" 
exit status 1

Anyone know what could be causing this?

**Comment by didip** [comment]
Did you set password for your PostgreSQL user? If so, you need to set that password on `PGPASSWORD` environment variable when running go-bootstrap.

**Comment by Qfulsher** [comment]
Yeah I have the user setup in PostgreSQL, how do you set that environment variable?

**Comment by Qfulsher** [comment]
For anyone with this issue, to set the environmental variable just run 

'export PGPASSWORD=\'{user-password-here}\''

then it should run just fine.
