### ISSUE TITLE
go get github.com/mattn/go-sqlite3 fails on OSX 10.10.3 (go1.4.2 darwin/amd64), so go-bootstrap fails too

### ISSUE THREAD

**Issue by sapiens-sapide** [go-bootstrap/go-bootstrap#29]
is it possible to run go-bootstrap without github.com/mattn/go-sqlite3 ?

**Comment by didip** [comment]
Unfortunately not, see https://github.com/go-bootstrap/go-bootstrap/issues/8 for more context.

The migration files under https://github.com/go-bootstrap/go-bootstrap/tree/master/blank/migrations is highly dependent on that project.

A few people, including myself, have reached out to @mattes convincing him to break out the `migrate` project per specific driver. It looks like he is making progress.

**Comment by didip** [comment]
We now uses `rnuble/pgmgr` as db migration tool.

**Comment by sapiens-sapide** [comment]
Thanks ! :-)

On 6 Jun 2015, at 19:21, Didip Kerabat wrote:

> We now uses `rnuble/pgmgr` as db migration tool.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/go-bootstrap/go-bootstrap/issues/29#issuecomment-109619647

|||||||||||||||||||||||||||||||||||||||||||
Stanislas SABATIER
sapiens.sapide
|||||||||||||||||||||||||||||||||||||||||||
Ce compte email est opéré par MAILDEN, le service de email qui 
protège nos données.
