### ISSUE TITLE
Skeleton app doesn't run on Windows

### ISSUE THREAD

**Issue by dulsonan** [go-bootstrap/go-bootstrap#32]
It's probably worth updating the "Prerequisites" list on the github site to include "a unix based operating system"; running on Windows give this error:

````
PS > go run .\main.go
time="2015-06-10T09:58:27-04:00" level=fatal msg="blank output when reading current user."
exit status 1
````

Due to the code in `libunix` expecting to be able to shell out and invoke a unix command to retrieve the user name.

**Comment by didip** [comment]
ah bummer, i'll update the docs
