### ISSUE TITLE
pgmgr: command not found

### ISSUE THREAD

**Issue by drichardson** [go-bootstrap/go-bootstrap#37]
Following the instructions on the README and I got some output like this:

    $ $GOPATH/bin/go-bootstrap -dir github.com/drichardson/howdy
    2015/12/29 21:51:54 Creating /Users/doug/test/src/github.com/drichardson/howdy...
    2015/12/29 21:51:54 Copying a blank project to /Users/doug/test/src/github.com/drichardson/howdy...
    2015/12/29 21:51:54 Replacing placeholder variables on drichardson/howdy...
    2015/12/29 21:51:54 Running go get github.com/rnubel/pgmgr...
    2015/12/29 21:51:54 Creating database howdy...
    scripts/db-bootstrap: line 4: pgmgr: command not found
    Running migrations...
    scripts/db-bootstrap: line 7: pgmgr: command not found
    Creating database howdy-test
    scripts/db-bootstrap: line 10: pgmgr: command not found
    Running migration on postgres://doug@localhost:5432/howdy-test?sslmode=disable...
    scripts/db-bootstrap: line 13: pgmgr: command not found
    2015/12/29 21:51:54 Running go get ./...

I had created a new Go workspace for the project, and it turned out $GOPATH/bin wasn't in my PATH. Might want to update the README to have a new step 2, like:

    PATH=$PATH:$GOPATH/bin

**Comment by didip** [comment]
Ah thanks for the feedback!

**Comment by didip** [comment]
Done. It is now mentioned as part of prerequisites.
