### ISSUE TITLE
clarification needed on templates

### ISSUE THREAD

**Issue by tvmaly** [go-bootstrap/go-bootstrap#44]
I am new to your project, and I was having a little difficulty understanding the documentation.

Core: If you don't want a database

I was interested to know how I could use this template option as I did not want to use a database.

How could I go about using this option?

**Comment by didip** [comment]
Hi @tvmaly, thanks for the interest in the project.

To use the core template, pass the following flag:
```
-template=core
```

I will update the docs to document this better.

**Comment by tvmaly** [comment]
thank you
