### ISSUE TITLE
Running database migrations fails when generating new project

### ISSUE THREAD

**Issue by muminoff** [go-bootstrap/go-bootstrap#9]
Hi.

I followed instruction how to generate new project, but `main.go` execution fails here:

```shell
2015/05/08 10:15:53 Running database migrations on postgres://sardor@localhost:5432/{project-name}?sslmode=disable...
2015/05/08 10:15:53 pq: password authentication failed for user "sardor"
```

I know, this is not go-bootstrap issue, this is related with my postgresql user, but "sardor" user is superuser.

```shell
sardor@geekbot:~/.gvm/pkgsets/go1.4/global/src/github.com/go-bootstrap/go-bootstrap$ sudo su postgres
postgres@geekbot:/home/sardor/.gvm/pkgsets/go1.4/global/src/github.com/go-bootstrap/go-bootstrap$ psql
psql (9.3.6)
Type "help" for help.

postgres=# \du
                              List of roles
  Role name  |                   Attributes                   | Member of 
-------------+------------------------------------------------+-----------
 digmaster   |                                                | {}
 drivers     |                                                | {}
 login       |                                                | {}
 newsdig     |                                                | {}
 postgres    | Superuser, Create role, Create DB, Replication | {}
 sardor      | Superuser, Create role, Create DB, Replication+| {}
             | Password valid until 2015-05-08 00:00:00+09    | 
 tarjimonlar |                                                | {}
 test        |                                                | {}

```

I think, this seems to be fixed in https://github.com/mattes/migrate but do you have any suggestions?

OS: Ubuntu 14.04.2 LTS
PostgreSQL: 9.3.6

**Comment by didip** [comment]
Ah, this must be because you need to pass password explicitly. What's the output if you run the migration by hand?

```
migrate -url postgres://sardor:$YOUR_PASSWORD_HERE@localhost:5432/$PROJECT_NAME?sslmode=disable -path $GOPATH/src/path/to/project/migrations up
```

**Comment by muminoff** [comment]
```shell

**Comment by muminoff** [comment]
```shell
sardor@geekbot:~/.gvm/pkgsets/go1.4/global/src/github.com/go-bootstrap/go-bootstrap$ migrate -url postgres://sardor:qwe123@localhost:5432/goweb?sslmode=disable -path /home/sardor/.gvm/pkgsets/go1.4/global/src/github.com/go-bootstrap/go-bootstrap/ up
pq: password authentication failed for user "sardor" 


0.0049 seconds
```

**Comment by didip** [comment]
Seems like the password is not passed correctly. Can you file an issue on  https://github.com/mattes/migrate page? Perhaps the author can shine some lights into this.

**Comment by dfwmountainbiker** [comment]
For testing, to get past the issue, I had to edit /etc/postgresql/9.3/main/pg_hba.conf  [version 9.3, Ubuntu) and remove the md5, peer for "trust".  This is not secure, and shouldn't be done in production.

**Comment by didip** [comment]
@dfwmountainbiker Ah, I had forgotten I did that too.
 @muminoff If this is a development machine, can you try the work around so you are unstuck?

**Comment by rnubel** [comment]
Per my comment on https://github.com/mattes/migrate/issues/41#issuecomment-100343811, I think passwords can be sent in the connection string, but as a query parameter. @muminoff, try this and see if it works better:

```migrate -url postgres://sardor@localhost:5432/$PROJECT_NAME?sslmode=disable&password=$YOUR_PASSWORD_HERE -path $GOPATH/src/path/to/project/migrations up```

**Comment by didip** [comment]
@muminoff I have updated the code the handler password through `$PGPASSWORD` environment variable. See: https://github.com/go-bootstrap/go-bootstrap/commit/f49a65180dc847fb012009e6345aa83f62c086c0

Can you try and see if that works for you?

**Comment by muminoff** [comment]
@rnubel @didip I can't access my Ubuntu machine now. Will try out tomorrow.

**Comment by JensChrG** [comment]
@didip you need to escape the ampersands in the arguments to migrate in scripts/db-bootstrap.sh for it to work.

**Comment by didip** [comment]
@JensChrG Thanks for the heads up!

**Comment by tbruyelle** [comment]
I had the same issue while running the go-bootstrap binary. 
Then I set the PGPASSWORD env and it passed.

**Comment by didip** [comment]
@tbruyelle Glad that the `PGPASSWORD` helped.

**Comment by didip** [comment]
Seems like this issue is solved through `PGPASSWORD`.
